import type { Metadata } from "next";
import { FileText, FileSpreadsheet, FileBarChart2 } from "lucide-react";
import { PageContainer } from "@/components/layout/page-container";
import { PageHeader } from "@/components/ui/page-header";
import { StatCard } from "@/components/ui/stat-card";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { ReportQuickActions } from "@/components/reports/report-quick-actions";
import { ReportActionsBar } from "@/components/reports/report-actions-bar";
import { requireAuth } from "@/lib/api-helpers";
import { reportService } from "@/features/reports/report.service";

export const metadata: Metadata = {
  title: "Reports & Analytics — Birhane Genet St. Mary Church",
};

function formatDateTime(iso: Date | string) {
  return new Date(iso).toLocaleString("en-US", { month: "short", day: "2-digit", year: "numeric", hour: "numeric", minute: "2-digit" });
}

export default async function ReportsOverviewPage() {
  await requireAuth();
  const s = await reportService.overview();

  return (
    <PageContainer>
      <PageHeader
        breadcrumb={[
          { label: "Home", href: "/dashboard" },
          { label: "Reports & Analytics", href: "/reports" },
          { label: "Overview" },
        ]}
        title="Reports & Analytics"
        actions={<ReportActionsBar />}
      />

      <div className="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-2">
        <StatCard label="Total Reports Generated" value={String(s.totalGenerated)} icon={FileBarChart2} iconBg="bg-primary-light" iconColor="text-primary" />
        <StatCard label="Report Categories" value={String(s.reportsByCategory.length)} icon={FileText} iconBg="bg-info-bg" iconColor="text-info" />
      </div>

      <Card className="mb-5">
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
        </CardHeader>
        {s.recentReports.length === 0 ? (
          <EmptyState
            title="No reports generated yet"
            description="Use the Create Report button above to generate your first report. It will appear here instantly."
          />
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Category</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Generated On</TableHead>
                <TableHead>Format</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {s.recentReports.map((r: { id: string; name: string; category: string; generatedBy: { name: string }; createdAt: Date | string; format: "PDF" | "Excel"; status: string }) => (
                <TableRow key={r.id}>
                  <TableCell className="font-semibold text-text-primary">{r.name}</TableCell>
                  <TableCell className="text-text-secondary">{r.category}</TableCell>
                  <TableCell className="text-text-secondary">{r.generatedBy.name}</TableCell>
                  <TableCell className="text-text-secondary">{formatDateTime(r.createdAt)}</TableCell>
                  <TableCell>
                    <span className="inline-flex items-center gap-1 text-text-secondary">
                      {r.format === "PDF" ? <FileText size={14} /> : <FileSpreadsheet size={14} />}
                      {r.format}
                    </span>
                  </TableCell>
                  <TableCell><Badge tone="success">{r.status}</Badge></TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </Card>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <ReportQuickActions />
      </div>
    </PageContainer>
  );
}
